version: '2'

services:
    
    message-bus:
        image: library/rabbitmq:3.6-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
        ports:
            - 15672:15672

    broadcast:
        build: ./broadcast
        links:
            - message-bus
        environment:
            - EXCHANGE_NAME=broadcast
        volumes:
            - ./broadcast/src/app:/src/app
            - ./nodejs-library:/src/library/

    worker:
        build: ./worker
        links:
            - message-bus
        environment:
            - EXCHANGE_NAME=broadcast
        volumes:
            - ./worker/src/app:/src/app
            - ./nodejs-library:/src/library/

    worker-python:
        build: ./worker-python
        links:
            - message-bus
        environment:
            - EXCHANGE_NAME=broadcast
        volumes:
            - ./worker-python/src:/src
