version: '2'

services:
    
    message-bus:
        image: library/rabbitmq:3.6-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
        ports:
            - 15672:15672

    dispatcher-a:
        links:
            - message-bus
        build: ./application
        environment:
            - EXCHANGE_NAME=channelA
            - ROUTING_KEY=defaultRoute
        volumes:
            - ./application/src/app:/src/app

    dispatcher-b:
        links:
            - message-bus
        build: ./application
        environment:
            - EXCHANGE_NAME=channelB
            - ROUTING_KEY=defaultRoute
        volumes:
            - ./application/src/app:/src/app

    worker-a:
        links:
            - message-bus
        build: ./worker
        environment:
            - QUEUE_NAME=workingPipeA
        volumes:
            - ./worker/src/app:/src/app

    worker-b:
        links:
            - message-bus
        build: ./worker
        environment:
            - QUEUE_NAME=workingPipeB
        volumes:
            - ./worker/src/app:/src/app

    worker-c:
        links:
            - message-bus
        build: ./worker
        environment:
            - QUEUE_NAME=workingPipeC
        volumes:
            - ./worker/src/app:/src/app
