apiVersion: v1
kind: Service
metadata:
  name: bus
spec:
  clusterIP: None
  ports:
  - name: rabbit
    port: 15672
    targetPort: 15672
  selector:
    app: rabbit-sandbox
    tier: bus

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitsandbox-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitsandbox
      tier: bus
  template:
    metadata:
      labels:
        app: rabbitsandbox
        tier: bus
    spec:
      containers:
      - name: bus
        image: library/rabbitmq:3.6-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbit
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbit

